package summarizer

import "github.com/nhirsama/yukibot/internal/contracts"

// SummarizerMigrations is the summarizer schema, translated from the Python
// SQLite migrations to PostgreSQL for the Go process database.
var SummarizerMigrations = []contracts.Migration{
	{
		Scope:       "summarizer",
		Version:     1,
		Description: "create summary rules and successful run history",
		Statements: []string{
			`
			CREATE TABLE summarizer_rules (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				source_chat_id bigint NOT NULL,
				source_topic_id bigint,
				source_username text,
				destination_chat_id bigint NOT NULL,
				destination_topic_id bigint,
				destination_username text,
				window_seconds integer NOT NULL
					CHECK (window_seconds BETWEEN 60 AND 2592000),
				enabled boolean NOT NULL DEFAULT true,
				created_at timestamptz NOT NULL DEFAULT now(),
				updated_at timestamptz NOT NULL DEFAULT now()
			)
			`,
			`
			CREATE INDEX summarizer_rules_source_idx
			ON summarizer_rules (source_chat_id, source_topic_id, enabled)
			`,
			`
			CREATE TABLE summarizer_runs (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				rule_id bigint NOT NULL,
				started_at timestamptz NOT NULL,
				completed_at timestamptz NOT NULL,
				first_message_id bigint NOT NULL CHECK (first_message_id > 0),
				last_message_id bigint NOT NULL CHECK (last_message_id >= first_message_id),
				message_count integer NOT NULL CHECK (message_count > 0),
				provider text NOT NULL,
				model text NOT NULL,
				prompt_version integer NOT NULL CHECK (prompt_version > 0),
				output_json text NOT NULL,
				created_at timestamptz NOT NULL DEFAULT now(),
				FOREIGN KEY (rule_id) REFERENCES summarizer_rules(id) ON DELETE CASCADE
			)
			`,
			`
			CREATE INDEX summarizer_runs_rule_idx
			ON summarizer_runs (rule_id, id DESC)
			`,
		},
	},
	{
		Scope:       "summarizer",
		Version:     2,
		Description: "create command-managed summary model configuration",
		Statements: []string{
			`
			CREATE TABLE summarizer_model_config (
				id integer PRIMARY KEY CHECK (id = 1),
				provider text NOT NULL,
				model text NOT NULL,
				api_key text,
				base_url text,
				input_token_limit integer NOT NULL
					CHECK (input_token_limit > output_token_limit + 2000),
				output_token_limit integer NOT NULL CHECK (output_token_limit > 0),
				temperature double precision NOT NULL CHECK (temperature BETWEEN 0 AND 2),
				timeout double precision NOT NULL CHECK (timeout > 0 AND timeout <= 1800),
				max_retries integer NOT NULL CHECK (max_retries BETWEEN 0 AND 10),
				updated_at timestamptz NOT NULL DEFAULT now()
			)
			`,
		},
	},
	{
		Scope:       "summarizer",
		Version:     3,
		Description: "add summary prompt and concurrency configuration",
		Statements: []string{
			`
			ALTER TABLE summarizer_model_config
			ADD COLUMN prompt_preset text NOT NULL DEFAULT 'focused'
				CHECK (prompt_preset IN ('focused', 'decisions', 'technical', 'digest'))
			`,
			`
			ALTER TABLE summarizer_model_config
			ADD COLUMN custom_prompt text
				CHECK (custom_prompt IS NULL OR length(custom_prompt) <= 4000)
			`,
			`
			ALTER TABLE summarizer_model_config
			ADD COLUMN max_concurrency integer NOT NULL DEFAULT 3
				CHECK (max_concurrency BETWEEN 1 AND 8)
			`,
		},
	},
}
