"""Reusable, Telegram-SDK-independent forwarding feature."""

from .album import AlbumBuffer
from .errors import (
    DeliveryResultMismatch,
    ForwarderError,
    MessageNotFound,
    MessageNotModified,
    NativeForwardUnsupported,
    PartialDeliveryState,
    PermanentDeliveryError,
    RetryAfter,
    RouteCycleError,
    RouteNotFoundError,
)
from .forwarder import Forwarder
from .memory import (
    InMemoryManagedTopicRepository,
    InMemoryMessageLinkRepository,
    InMemoryPollCursorRepository,
    InMemoryRouteRepository,
)
from .models import (
    ChatIdentity,
    ContentType,
    DestinationEndpoint,
    ForwardMode,
    IncomingMessage,
    ManagedTopic,
    MessageFilter,
    MessageLink,
    MessageRef,
    MessagesDeleted,
    PollCursor,
    Route,
    RouteDraft,
    ServiceKind,
    ServiceMessage,
    SourceEndpoint,
    normalize_general_topic,
)
from .ports import (
    ManagedTopicRepository,
    MessageLinkRepository,
    PollCursorRepository,
    RouteRepository,
    TelegramGateway,
    TelegramSourceGateway,
)
from .routing import assert_acyclic_routes
from .service import (
    DeliveryFailure,
    DeliveryOutcome,
    ForwarderOptions,
    ForwarderService,
    ForwardingReport,
    SyncFailure,
    SyncOperation,
    SyncReport,
    format_service_message,
)
from .topics import ManagedTopicService

__all__ = [
    "AlbumBuffer",
    "ChatIdentity",
    "ContentType",
    "DeliveryFailure",
    "DeliveryOutcome",
    "DeliveryResultMismatch",
    "DestinationEndpoint",
    "ForwardMode",
    "Forwarder",
    "ForwarderError",
    "ForwarderOptions",
    "ForwarderService",
    "ForwardingReport",
    "InMemoryManagedTopicRepository",
    "InMemoryMessageLinkRepository",
    "InMemoryPollCursorRepository",
    "InMemoryRouteRepository",
    "IncomingMessage",
    "ManagedTopic",
    "ManagedTopicRepository",
    "ManagedTopicService",
    "MessageFilter",
    "MessageLink",
    "MessageLinkRepository",
    "MessageNotFound",
    "MessageNotModified",
    "MessageRef",
    "MessagesDeleted",
    "NativeForwardUnsupported",
    "PartialDeliveryState",
    "PermanentDeliveryError",
    "PollCursor",
    "PollCursorRepository",
    "RetryAfter",
    "Route",
    "RouteCycleError",
    "RouteDraft",
    "RouteNotFoundError",
    "RouteRepository",
    "ServiceKind",
    "ServiceMessage",
    "SourceEndpoint",
    "SyncFailure",
    "SyncOperation",
    "SyncReport",
    "TelegramGateway",
    "TelegramSourceGateway",
    "assert_acyclic_routes",
    "format_service_message",
    "normalize_general_topic",
]
