// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forwarder.sql

package dbsql

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRouteChatRefs = `-- name: CountRouteChatRefs :one
SELECT COUNT(*)::bigint
FROM forwarder_routes
WHERE source_chat_id = $1 OR destination_chat_id = $1
`

func (q *Queries) CountRouteChatRefs(ctx context.Context, sourceChatID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRouteChatRefs, sourceChatID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteChatAccess = `-- name: DeleteChatAccess :exec
DELETE FROM forwarder_chat_access WHERE chat_id = $1
`

func (q *Queries) DeleteChatAccess(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, deleteChatAccess, chatID)
	return err
}

const deleteMessageLink = `-- name: DeleteMessageLink :exec
DELETE FROM forwarder_message_links
WHERE route_id = $1 AND source_chat_id = $2 AND source_message_id = $3
`

type DeleteMessageLinkParams struct {
	RouteID         int64
	SourceChatID    int64
	SourceMessageID int64
}

func (q *Queries) DeleteMessageLink(ctx context.Context, arg DeleteMessageLinkParams) error {
	_, err := q.db.Exec(ctx, deleteMessageLink, arg.RouteID, arg.SourceChatID, arg.SourceMessageID)
	return err
}

const deleteProcessingJobs = `-- name: DeleteProcessingJobs :exec
DELETE FROM forwarder_jobs
WHERE id = ANY($1::bigint[]) AND state = 'processing'
`

func (q *Queries) DeleteProcessingJobs(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, deleteProcessingJobs, dollar_1)
	return err
}

const deleteRoute = `-- name: DeleteRoute :execrows
DELETE FROM forwarder_routes WHERE id = $1
`

func (q *Queries) DeleteRoute(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoute, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failProcessingJobs = `-- name: FailProcessingJobs :exec
UPDATE forwarder_jobs
SET state = 'failed', last_error = $2, updated_at = now()
WHERE id = ANY($1::bigint[]) AND state = 'processing'
`

type FailProcessingJobsParams struct {
	Column1   []int64
	LastError *string
}

func (q *Queries) FailProcessingJobs(ctx context.Context, arg FailProcessingJobsParams) error {
	_, err := q.db.Exec(ctx, failProcessingJobs, arg.Column1, arg.LastError)
	return err
}

const findLinksByMessageID = `-- name: FindLinksByMessageID :many
SELECT route_id, source_chat_id, source_message_id, destination_chat_id, destination_message_id, delivery_mode
FROM forwarder_message_links
WHERE source_message_id = $1
ORDER BY route_id, source_chat_id
`

type FindLinksByMessageIDRow struct {
	RouteID              int64
	SourceChatID         int64
	SourceMessageID      int64
	DestinationChatID    int64
	DestinationMessageID int64
	DeliveryMode         string
}

func (q *Queries) FindLinksByMessageID(ctx context.Context, sourceMessageID int64) ([]FindLinksByMessageIDRow, error) {
	rows, err := q.db.Query(ctx, findLinksByMessageID, sourceMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindLinksByMessageIDRow
	for rows.Next() {
		var i FindLinksByMessageIDRow
		if err := rows.Scan(
			&i.RouteID,
			&i.SourceChatID,
			&i.SourceMessageID,
			&i.DestinationChatID,
			&i.DestinationMessageID,
			&i.DeliveryMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLinksBySource = `-- name: FindLinksBySource :many
SELECT route_id, source_chat_id, source_message_id, destination_chat_id, destination_message_id, delivery_mode
FROM forwarder_message_links
WHERE source_chat_id = $1 AND source_message_id = $2
ORDER BY route_id
`

type FindLinksBySourceParams struct {
	SourceChatID    int64
	SourceMessageID int64
}

type FindLinksBySourceRow struct {
	RouteID              int64
	SourceChatID         int64
	SourceMessageID      int64
	DestinationChatID    int64
	DestinationMessageID int64
	DeliveryMode         string
}

func (q *Queries) FindLinksBySource(ctx context.Context, arg FindLinksBySourceParams) ([]FindLinksBySourceRow, error) {
	rows, err := q.db.Query(ctx, findLinksBySource, arg.SourceChatID, arg.SourceMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindLinksBySourceRow
	for rows.Next() {
		var i FindLinksBySourceRow
		if err := rows.Scan(
			&i.RouteID,
			&i.SourceChatID,
			&i.SourceMessageID,
			&i.DestinationChatID,
			&i.DestinationMessageID,
			&i.DeliveryMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManagedTopic = `-- name: GetManagedTopic :one
SELECT source_chat_id, source_topic_id, destination_chat_id, topic_id, title
FROM forwarder_managed_topics
WHERE source_chat_id = $1 AND source_topic_id = $2 AND destination_chat_id = $3
`

type GetManagedTopicParams struct {
	SourceChatID      int64
	SourceTopicID     int64
	DestinationChatID int64
}

type GetManagedTopicRow struct {
	SourceChatID      int64
	SourceTopicID     int64
	DestinationChatID int64
	TopicID           int64
	Title             string
}

func (q *Queries) GetManagedTopic(ctx context.Context, arg GetManagedTopicParams) (GetManagedTopicRow, error) {
	row := q.db.QueryRow(ctx, getManagedTopic, arg.SourceChatID, arg.SourceTopicID, arg.DestinationChatID)
	var i GetManagedTopicRow
	err := row.Scan(
		&i.SourceChatID,
		&i.SourceTopicID,
		&i.DestinationChatID,
		&i.TopicID,
		&i.Title,
	)
	return i, err
}

const getMessageLink = `-- name: GetMessageLink :one
SELECT route_id, source_chat_id, source_message_id, destination_chat_id, destination_message_id, delivery_mode
FROM forwarder_message_links
WHERE route_id = $1 AND source_chat_id = $2 AND source_message_id = $3
`

type GetMessageLinkParams struct {
	RouteID         int64
	SourceChatID    int64
	SourceMessageID int64
}

type GetMessageLinkRow struct {
	RouteID              int64
	SourceChatID         int64
	SourceMessageID      int64
	DestinationChatID    int64
	DestinationMessageID int64
	DeliveryMode         string
}

func (q *Queries) GetMessageLink(ctx context.Context, arg GetMessageLinkParams) (GetMessageLinkRow, error) {
	row := q.db.QueryRow(ctx, getMessageLink, arg.RouteID, arg.SourceChatID, arg.SourceMessageID)
	var i GetMessageLinkRow
	err := row.Scan(
		&i.RouteID,
		&i.SourceChatID,
		&i.SourceMessageID,
		&i.DestinationChatID,
		&i.DestinationMessageID,
		&i.DeliveryMode,
	)
	return i, err
}

const getPollCursor = `-- name: GetPollCursor :one
SELECT source_chat_id, last_message_id FROM forwarder_poll_cursors WHERE source_chat_id = $1
`

type GetPollCursorRow struct {
	SourceChatID  int64
	LastMessageID int64
}

func (q *Queries) GetPollCursor(ctx context.Context, sourceChatID int64) (GetPollCursorRow, error) {
	row := q.db.QueryRow(ctx, getPollCursor, sourceChatID)
	var i GetPollCursorRow
	err := row.Scan(&i.SourceChatID, &i.LastMessageID)
	return i, err
}

const insertChatAccessIgnore = `-- name: InsertChatAccessIgnore :exec
INSERT INTO forwarder_chat_access (chat_id, username, invite_link)
VALUES ($1, $2, $3)
ON CONFLICT (chat_id) DO NOTHING
`

type InsertChatAccessIgnoreParams struct {
	ChatID     int64
	Username   *string
	InviteLink *string
}

func (q *Queries) InsertChatAccessIgnore(ctx context.Context, arg InsertChatAccessIgnoreParams) error {
	_, err := q.db.Exec(ctx, insertChatAccessIgnore, arg.ChatID, arg.Username, arg.InviteLink)
	return err
}

const insertJob = `-- name: InsertJob :execrows
INSERT INTO forwarder_jobs (kind, deduplication_key, group_key, payload_json, available_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (deduplication_key) DO NOTHING
`

type InsertJobParams struct {
	Kind             string
	DeduplicationKey string
	GroupKey         *string
	PayloadJson      json.RawMessage
	AvailableAt      pgtype.Timestamptz
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertJob,
		arg.Kind,
		arg.DeduplicationKey,
		arg.GroupKey,
		arg.PayloadJson,
		arg.AvailableAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRoute = `-- name: InsertRoute :one
INSERT INTO forwarder_routes (
    source_chat_id, source_topic_id, destination_chat_id, destination_topic_id,
    mode, filter_json, enabled, fallback_to_copy, source_username, destination_username,
    poll_interval_seconds
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertRouteParams struct {
	SourceChatID        int64
	SourceTopicID       *int64
	DestinationChatID   int64
	DestinationTopicID  *int64
	Mode                string
	FilterJson          json.RawMessage
	Enabled             bool
	FallbackToCopy      bool
	SourceUsername      *string
	DestinationUsername *string
	PollIntervalSeconds *int32
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRoute,
		arg.SourceChatID,
		arg.SourceTopicID,
		arg.DestinationChatID,
		arg.DestinationTopicID,
		arg.Mode,
		arg.FilterJson,
		arg.Enabled,
		arg.FallbackToCopy,
		arg.SourceUsername,
		arg.DestinationUsername,
		arg.PollIntervalSeconds,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRouteWithID = `-- name: InsertRouteWithID :one
INSERT INTO forwarder_routes (
    id, source_chat_id, source_topic_id, destination_chat_id, destination_topic_id,
    mode, filter_json, enabled, fallback_to_copy, source_username, destination_username,
    poll_interval_seconds
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type InsertRouteWithIDParams struct {
	ID                  int64
	SourceChatID        int64
	SourceTopicID       *int64
	DestinationChatID   int64
	DestinationTopicID  *int64
	Mode                string
	FilterJson          json.RawMessage
	Enabled             bool
	FallbackToCopy      bool
	SourceUsername      *string
	DestinationUsername *string
	PollIntervalSeconds *int32
}

func (q *Queries) InsertRouteWithID(ctx context.Context, arg InsertRouteWithIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRouteWithID,
		arg.ID,
		arg.SourceChatID,
		arg.SourceTopicID,
		arg.DestinationChatID,
		arg.DestinationTopicID,
		arg.Mode,
		arg.FilterJson,
		arg.Enabled,
		arg.FallbackToCopy,
		arg.SourceUsername,
		arg.DestinationUsername,
		arg.PollIntervalSeconds,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listChatAccess = `-- name: ListChatAccess :many
SELECT chat_id, title, username, invite_link
FROM forwarder_chat_access
WHERE chat_id = ANY($1::bigint[])
ORDER BY chat_id
`

type ListChatAccessRow struct {
	ChatID     int64
	Title      *string
	Username   *string
	InviteLink *string
}

func (q *Queries) ListChatAccess(ctx context.Context, dollar_1 []int64) ([]ListChatAccessRow, error) {
	rows, err := q.db.Query(ctx, listChatAccess, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatAccessRow
	for rows.Next() {
		var i ListChatAccessRow
		if err := rows.Scan(
			&i.ChatID,
			&i.Title,
			&i.Username,
			&i.InviteLink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, source_chat_id, source_topic_id, destination_chat_id, destination_topic_id,
       mode, filter_json, enabled, fallback_to_copy, source_username, destination_username,
       poll_interval_seconds
FROM forwarder_routes
ORDER BY id
`

func (q *Queries) ListRoutes(ctx context.Context) ([]ForwarderRoute, error) {
	rows, err := q.db.Query(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForwarderRoute
	for rows.Next() {
		var i ForwarderRoute
		if err := rows.Scan(
			&i.ID,
			&i.SourceChatID,
			&i.SourceTopicID,
			&i.DestinationChatID,
			&i.DestinationTopicID,
			&i.Mode,
			&i.FilterJson,
			&i.Enabled,
			&i.FallbackToCopy,
			&i.SourceUsername,
			&i.DestinationUsername,
			&i.PollIntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesForSourceChat = `-- name: ListRoutesForSourceChat :many
SELECT id, source_chat_id, source_topic_id, destination_chat_id, destination_topic_id,
       mode, filter_json, enabled, fallback_to_copy, source_username, destination_username,
       poll_interval_seconds
FROM forwarder_routes
WHERE source_chat_id = $1
ORDER BY id
`

func (q *Queries) ListRoutesForSourceChat(ctx context.Context, sourceChatID int64) ([]ForwarderRoute, error) {
	rows, err := q.db.Query(ctx, listRoutesForSourceChat, sourceChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForwarderRoute
	for rows.Next() {
		var i ForwarderRoute
		if err := rows.Scan(
			&i.ID,
			&i.SourceChatID,
			&i.SourceTopicID,
			&i.DestinationChatID,
			&i.DestinationTopicID,
			&i.Mode,
			&i.FilterJson,
			&i.Enabled,
			&i.FallbackToCopy,
			&i.SourceUsername,
			&i.DestinationUsername,
			&i.PollIntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobsProcessing = `-- name: MarkJobsProcessing :exec
UPDATE forwarder_jobs
SET state = 'processing', attempts = attempts + 1, updated_at = now()
WHERE id = ANY($1::bigint[]) AND state = 'pending'
`

func (q *Queries) MarkJobsProcessing(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markJobsProcessing, dollar_1)
	return err
}

const recoverProcessingJobs = `-- name: RecoverProcessingJobs :execrows
UPDATE forwarder_jobs
SET state = 'pending', updated_at = now()
WHERE state = 'processing'
`

func (q *Queries) RecoverProcessingJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverProcessingJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleProcessingJobs = `-- name: RescheduleProcessingJobs :exec
UPDATE forwarder_jobs
SET state = 'pending', available_at = $2, last_error = $3, updated_at = now()
WHERE id = ANY($1::bigint[]) AND state = 'processing'
`

type RescheduleProcessingJobsParams struct {
	Column1     []int64
	AvailableAt pgtype.Timestamptz
	LastError   *string
}

func (q *Queries) RescheduleProcessingJobs(ctx context.Context, arg RescheduleProcessingJobsParams) error {
	_, err := q.db.Exec(ctx, rescheduleProcessingJobs, arg.Column1, arg.AvailableAt, arg.LastError)
	return err
}

const selectDueGroupJobs = `-- name: SelectDueGroupJobs :many
SELECT id, kind, group_key, payload_json, attempts, available_at
FROM forwarder_jobs
WHERE state = 'pending' AND group_key = $1 AND available_at <= $2
ORDER BY id
FOR UPDATE
`

type SelectDueGroupJobsParams struct {
	GroupKey    *string
	AvailableAt pgtype.Timestamptz
}

type SelectDueGroupJobsRow struct {
	ID          int64
	Kind        string
	GroupKey    *string
	PayloadJson json.RawMessage
	Attempts    int32
	AvailableAt pgtype.Timestamptz
}

func (q *Queries) SelectDueGroupJobs(ctx context.Context, arg SelectDueGroupJobsParams) ([]SelectDueGroupJobsRow, error) {
	rows, err := q.db.Query(ctx, selectDueGroupJobs, arg.GroupKey, arg.AvailableAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectDueGroupJobsRow
	for rows.Next() {
		var i SelectDueGroupJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.GroupKey,
			&i.PayloadJson,
			&i.Attempts,
			&i.AvailableAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectHeadPendingJob = `-- name: SelectHeadPendingJob :one
SELECT id, kind, group_key, payload_json, attempts, available_at
FROM forwarder_jobs
WHERE state = 'pending'
ORDER BY id
LIMIT 1
FOR UPDATE
`

type SelectHeadPendingJobRow struct {
	ID          int64
	Kind        string
	GroupKey    *string
	PayloadJson json.RawMessage
	Attempts    int32
	AvailableAt pgtype.Timestamptz
}

func (q *Queries) SelectHeadPendingJob(ctx context.Context) (SelectHeadPendingJobRow, error) {
	row := q.db.QueryRow(ctx, selectHeadPendingJob)
	var i SelectHeadPendingJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.GroupKey,
		&i.PayloadJson,
		&i.Attempts,
		&i.AvailableAt,
	)
	return i, err
}

const slidePendingGroup = `-- name: SlidePendingGroup :exec
UPDATE forwarder_jobs
SET available_at = $1, updated_at = now()
WHERE group_key = $2 AND state = 'pending'
`

type SlidePendingGroupParams struct {
	AvailableAt pgtype.Timestamptz
	GroupKey    *string
}

func (q *Queries) SlidePendingGroup(ctx context.Context, arg SlidePendingGroupParams) error {
	_, err := q.db.Exec(ctx, slidePendingGroup, arg.AvailableAt, arg.GroupKey)
	return err
}

const syncRouteIDSequence = `-- name: SyncRouteIDSequence :one
SELECT setval(pg_get_serial_sequence('forwarder_routes', 'id'),
              (SELECT COALESCE(MAX(id), 1) FROM forwarder_routes))
`

func (q *Queries) SyncRouteIDSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, syncRouteIDSequence)
	var setval int64
	err := row.Scan(&setval)
	return setval, err
}

const updateRoute = `-- name: UpdateRoute :execrows
UPDATE forwarder_routes
SET source_chat_id = $2,
    source_topic_id = $3,
    destination_chat_id = $4,
    destination_topic_id = $5,
    mode = $6,
    filter_json = $7,
    enabled = $8,
    fallback_to_copy = $9,
    source_username = $10,
    destination_username = $11,
    poll_interval_seconds = $12
WHERE id = $1
`

type UpdateRouteParams struct {
	ID                  int64
	SourceChatID        int64
	SourceTopicID       *int64
	DestinationChatID   int64
	DestinationTopicID  *int64
	Mode                string
	FilterJson          json.RawMessage
	Enabled             bool
	FallbackToCopy      bool
	SourceUsername      *string
	DestinationUsername *string
	PollIntervalSeconds *int32
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRoute,
		arg.ID,
		arg.SourceChatID,
		arg.SourceTopicID,
		arg.DestinationChatID,
		arg.DestinationTopicID,
		arg.Mode,
		arg.FilterJson,
		arg.Enabled,
		arg.FallbackToCopy,
		arg.SourceUsername,
		arg.DestinationUsername,
		arg.PollIntervalSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertChatAccess = `-- name: UpsertChatAccess :exec
INSERT INTO forwarder_chat_access (chat_id, title, username, invite_link)
VALUES ($1, $2, $3, $4)
ON CONFLICT (chat_id) DO UPDATE
SET title = COALESCE(EXCLUDED.title, forwarder_chat_access.title),
    username = EXCLUDED.username,
    invite_link = EXCLUDED.invite_link,
    updated_at = now()
`

type UpsertChatAccessParams struct {
	ChatID     int64
	Title      *string
	Username   *string
	InviteLink *string
}

func (q *Queries) UpsertChatAccess(ctx context.Context, arg UpsertChatAccessParams) error {
	_, err := q.db.Exec(ctx, upsertChatAccess,
		arg.ChatID,
		arg.Title,
		arg.Username,
		arg.InviteLink,
	)
	return err
}

const upsertManagedTopic = `-- name: UpsertManagedTopic :exec
INSERT INTO forwarder_managed_topics (source_chat_id, source_topic_id, destination_chat_id, topic_id, title)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_chat_id, source_topic_id, destination_chat_id) DO UPDATE
SET topic_id = EXCLUDED.topic_id, title = EXCLUDED.title, updated_at = now()
`

type UpsertManagedTopicParams struct {
	SourceChatID      int64
	SourceTopicID     int64
	DestinationChatID int64
	TopicID           int64
	Title             string
}

func (q *Queries) UpsertManagedTopic(ctx context.Context, arg UpsertManagedTopicParams) error {
	_, err := q.db.Exec(ctx, upsertManagedTopic,
		arg.SourceChatID,
		arg.SourceTopicID,
		arg.DestinationChatID,
		arg.TopicID,
		arg.Title,
	)
	return err
}

const upsertMessageLink = `-- name: UpsertMessageLink :exec
INSERT INTO forwarder_message_links (
    route_id, source_chat_id, source_message_id, destination_chat_id, destination_message_id, delivery_mode
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (route_id, source_chat_id, source_message_id) DO UPDATE
SET destination_chat_id = EXCLUDED.destination_chat_id,
    destination_message_id = EXCLUDED.destination_message_id,
    delivery_mode = EXCLUDED.delivery_mode
`

type UpsertMessageLinkParams struct {
	RouteID              int64
	SourceChatID         int64
	SourceMessageID      int64
	DestinationChatID    int64
	DestinationMessageID int64
	DeliveryMode         string
}

func (q *Queries) UpsertMessageLink(ctx context.Context, arg UpsertMessageLinkParams) error {
	_, err := q.db.Exec(ctx, upsertMessageLink,
		arg.RouteID,
		arg.SourceChatID,
		arg.SourceMessageID,
		arg.DestinationChatID,
		arg.DestinationMessageID,
		arg.DeliveryMode,
	)
	return err
}

const upsertPollCursor = `-- name: UpsertPollCursor :exec
INSERT INTO forwarder_poll_cursors (source_chat_id, last_message_id)
VALUES ($1, $2)
ON CONFLICT (source_chat_id) DO UPDATE
SET last_message_id = GREATEST(forwarder_poll_cursors.last_message_id, EXCLUDED.last_message_id),
    updated_at = now()
`

type UpsertPollCursorParams struct {
	SourceChatID  int64
	LastMessageID int64
}

func (q *Queries) UpsertPollCursor(ctx context.Context, arg UpsertPollCursorParams) error {
	_, err := q.db.Exec(ctx, upsertPollCursor, arg.SourceChatID, arg.LastMessageID)
	return err
}
