// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: management.sql

package dbsql

import (
	"context"
)

const addAdmin = `-- name: AddAdmin :exec
INSERT INTO management_admins (user_id, granted_by)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
`

type AddAdminParams struct {
	UserID    int64
	GrantedBy int64
}

func (q *Queries) AddAdmin(ctx context.Context, arg AddAdminParams) error {
	_, err := q.db.Exec(ctx, addAdmin, arg.UserID, arg.GrantedBy)
	return err
}

const getModuleEnabled = `-- name: GetModuleEnabled :one
SELECT enabled FROM management_modules WHERE name = $1
`

func (q *Queries) GetModuleEnabled(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, getModuleEnabled, name)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const isAdmin = `-- name: IsAdmin :one
SELECT EXISTS(SELECT 1 FROM management_admins WHERE user_id = $1) AS is_admin
`

func (q *Queries) IsAdmin(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isAdmin, userID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const isCommandProcessed = `-- name: IsCommandProcessed :one
SELECT EXISTS(
    SELECT 1 FROM management_command_receipts
    WHERE account_id = $1 AND chat_id = $2 AND message_id = $3
) AS processed
`

type IsCommandProcessedParams struct {
	AccountID int64
	ChatID    int64
	MessageID int64
}

func (q *Queries) IsCommandProcessed(ctx context.Context, arg IsCommandProcessedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCommandProcessed, arg.AccountID, arg.ChatID, arg.MessageID)
	var processed bool
	err := row.Scan(&processed)
	return processed, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT user_id, granted_by FROM management_admins ORDER BY user_id
`

type ListAdminsRow struct {
	UserID    int64
	GrantedBy int64
}

func (q *Queries) ListAdmins(ctx context.Context) ([]ListAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminsRow
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(&i.UserID, &i.GrantedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommandProcessed = `-- name: MarkCommandProcessed :exec
INSERT INTO management_command_receipts (account_id, chat_id, message_id)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, chat_id, message_id) DO NOTHING
`

type MarkCommandProcessedParams struct {
	AccountID int64
	ChatID    int64
	MessageID int64
}

func (q *Queries) MarkCommandProcessed(ctx context.Context, arg MarkCommandProcessedParams) error {
	_, err := q.db.Exec(ctx, markCommandProcessed, arg.AccountID, arg.ChatID, arg.MessageID)
	return err
}

const removeAdmin = `-- name: RemoveAdmin :exec
DELETE FROM management_admins WHERE user_id = $1
`

func (q *Queries) RemoveAdmin(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, removeAdmin, userID)
	return err
}

const setModuleEnabled = `-- name: SetModuleEnabled :exec
INSERT INTO management_modules (name, enabled)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = now()
`

type SetModuleEnabledParams struct {
	Name    string
	Enabled bool
}

func (q *Queries) SetModuleEnabled(ctx context.Context, arg SetModuleEnabledParams) error {
	_, err := q.db.Exec(ctx, setModuleEnabled, arg.Name, arg.Enabled)
	return err
}
