// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsql

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type ForwarderChatAccess struct {
	ChatID     int64
	Title      *string
	Username   *string
	InviteLink *string
	UpdatedAt  pgtype.Timestamptz
}

type ForwarderJob struct {
	ID               int64
	Kind             string
	DeduplicationKey string
	GroupKey         *string
	PayloadJson      json.RawMessage
	State            string
	Attempts         int32
	AvailableAt      pgtype.Timestamptz
	LastError        *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ForwarderManagedTopic struct {
	SourceChatID      int64
	SourceTopicID     int64
	DestinationChatID int64
	TopicID           int64
	Title             string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type ForwarderMessageLink struct {
	RouteID              int64
	SourceChatID         int64
	SourceMessageID      int64
	DestinationChatID    int64
	DestinationMessageID int64
	DeliveryMode         string
	CreatedAt            pgtype.Timestamptz
}

type ForwarderPollCursor struct {
	SourceChatID  int64
	LastMessageID int64
	UpdatedAt     pgtype.Timestamptz
}

type ForwarderRoute struct {
	ID                  int64
	SourceChatID        int64
	SourceTopicID       *int64
	DestinationChatID   int64
	DestinationTopicID  *int64
	Mode                string
	FilterJson          json.RawMessage
	Enabled             bool
	FallbackToCopy      bool
	SourceUsername      *string
	DestinationUsername *string
	PollIntervalSeconds *int32
}

type ManagementAdmin struct {
	UserID    int64
	GrantedBy int64
	CreatedAt pgtype.Timestamptz
}

type ManagementCommandReceipt struct {
	AccountID   int64
	ChatID      int64
	MessageID   int64
	ProcessedAt pgtype.Timestamptz
}

type ManagementModule struct {
	Name      string
	Enabled   bool
	UpdatedAt pgtype.Timestamptz
}

type SummarizerModelConfig struct {
	ID               int32
	Provider         string
	Model            string
	ApiKey           *string
	BaseUrl          *string
	InputTokenLimit  int32
	OutputTokenLimit int32
	Temperature      float64
	Timeout          float64
	MaxRetries       int32
	PromptPreset     string
	CustomPrompt     *string
	MaxConcurrency   int32
	UpdatedAt        pgtype.Timestamptz
}

type SummarizerRule struct {
	ID                  int64
	SourceChatID        int64
	SourceTopicID       *int64
	SourceUsername      *string
	DestinationChatID   int64
	DestinationTopicID  *int64
	DestinationUsername *string
	WindowSeconds       int32
	Enabled             bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type SummarizerRun struct {
	ID             int64
	RuleID         int64
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	FirstMessageID int64
	LastMessageID  int64
	MessageCount   int32
	Provider       string
	Model          string
	PromptVersion  int32
	OutputJson     string
	CreatedAt      pgtype.Timestamptz
}

type YukibotSchemaMigration struct {
	Scope       string
	Version     int32
	Description string
	Checksum    string
	AppliedAt   pgtype.Timestamptz
}
