// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summarizer.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearSummaryModelConfig = `-- name: ClearSummaryModelConfig :execrows
DELETE FROM summarizer_model_config WHERE id = 1
`

func (q *Queries) ClearSummaryModelConfig(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, clearSummaryModelConfig)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSummaryRule = `-- name: DeleteSummaryRule :execrows
DELETE FROM summarizer_rules WHERE id = $1
`

func (q *Queries) DeleteSummaryRule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSummaryRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSummaryModelConfig = `-- name: GetSummaryModelConfig :one
SELECT provider, model, api_key, base_url, input_token_limit, output_token_limit,
       temperature, timeout, max_retries, prompt_preset, custom_prompt, max_concurrency
FROM summarizer_model_config
WHERE id = 1
`

type GetSummaryModelConfigRow struct {
	Provider         string
	Model            string
	ApiKey           *string
	BaseUrl          *string
	InputTokenLimit  int32
	OutputTokenLimit int32
	Temperature      float64
	Timeout          float64
	MaxRetries       int32
	PromptPreset     string
	CustomPrompt     *string
	MaxConcurrency   int32
}

func (q *Queries) GetSummaryModelConfig(ctx context.Context) (GetSummaryModelConfigRow, error) {
	row := q.db.QueryRow(ctx, getSummaryModelConfig)
	var i GetSummaryModelConfigRow
	err := row.Scan(
		&i.Provider,
		&i.Model,
		&i.ApiKey,
		&i.BaseUrl,
		&i.InputTokenLimit,
		&i.OutputTokenLimit,
		&i.Temperature,
		&i.Timeout,
		&i.MaxRetries,
		&i.PromptPreset,
		&i.CustomPrompt,
		&i.MaxConcurrency,
	)
	return i, err
}

const insertSummaryRule = `-- name: InsertSummaryRule :one
INSERT INTO summarizer_rules (
    source_chat_id, source_topic_id, source_username,
    destination_chat_id, destination_topic_id, destination_username,
    window_seconds, enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertSummaryRuleParams struct {
	SourceChatID        int64
	SourceTopicID       *int64
	SourceUsername      *string
	DestinationChatID   int64
	DestinationTopicID  *int64
	DestinationUsername *string
	WindowSeconds       int32
	Enabled             bool
}

func (q *Queries) InsertSummaryRule(ctx context.Context, arg InsertSummaryRuleParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSummaryRule,
		arg.SourceChatID,
		arg.SourceTopicID,
		arg.SourceUsername,
		arg.DestinationChatID,
		arg.DestinationTopicID,
		arg.DestinationUsername,
		arg.WindowSeconds,
		arg.Enabled,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSummaryRun = `-- name: InsertSummaryRun :exec
INSERT INTO summarizer_runs (
    rule_id, started_at, completed_at, first_message_id, last_message_id,
    message_count, provider, model, prompt_version, output_json
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertSummaryRunParams struct {
	RuleID         int64
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	FirstMessageID int64
	LastMessageID  int64
	MessageCount   int32
	Provider       string
	Model          string
	PromptVersion  int32
	OutputJson     string
}

func (q *Queries) InsertSummaryRun(ctx context.Context, arg InsertSummaryRunParams) error {
	_, err := q.db.Exec(ctx, insertSummaryRun,
		arg.RuleID,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FirstMessageID,
		arg.LastMessageID,
		arg.MessageCount,
		arg.Provider,
		arg.Model,
		arg.PromptVersion,
		arg.OutputJson,
	)
	return err
}

const listSummaryRules = `-- name: ListSummaryRules :many
SELECT id, source_chat_id, source_topic_id, source_username,
       destination_chat_id, destination_topic_id, destination_username,
       window_seconds, enabled
FROM summarizer_rules
ORDER BY id
`

type ListSummaryRulesRow struct {
	ID                  int64
	SourceChatID        int64
	SourceTopicID       *int64
	SourceUsername      *string
	DestinationChatID   int64
	DestinationTopicID  *int64
	DestinationUsername *string
	WindowSeconds       int32
	Enabled             bool
}

func (q *Queries) ListSummaryRules(ctx context.Context) ([]ListSummaryRulesRow, error) {
	rows, err := q.db.Query(ctx, listSummaryRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSummaryRulesRow
	for rows.Next() {
		var i ListSummaryRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceChatID,
			&i.SourceTopicID,
			&i.SourceUsername,
			&i.DestinationChatID,
			&i.DestinationTopicID,
			&i.DestinationUsername,
			&i.WindowSeconds,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSummaryRule = `-- name: UpdateSummaryRule :execrows
UPDATE summarizer_rules
SET source_chat_id = $2,
    source_topic_id = $3,
    source_username = $4,
    destination_chat_id = $5,
    destination_topic_id = $6,
    destination_username = $7,
    window_seconds = $8,
    enabled = $9,
    updated_at = now()
WHERE id = $1
`

type UpdateSummaryRuleParams struct {
	ID                  int64
	SourceChatID        int64
	SourceTopicID       *int64
	SourceUsername      *string
	DestinationChatID   int64
	DestinationTopicID  *int64
	DestinationUsername *string
	WindowSeconds       int32
	Enabled             bool
}

func (q *Queries) UpdateSummaryRule(ctx context.Context, arg UpdateSummaryRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSummaryRule,
		arg.ID,
		arg.SourceChatID,
		arg.SourceTopicID,
		arg.SourceUsername,
		arg.DestinationChatID,
		arg.DestinationTopicID,
		arg.DestinationUsername,
		arg.WindowSeconds,
		arg.Enabled,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSummaryModelConfig = `-- name: UpsertSummaryModelConfig :exec
INSERT INTO summarizer_model_config (
    id, provider, model, api_key, base_url, input_token_limit, output_token_limit,
    temperature, timeout, max_retries, prompt_preset, custom_prompt, max_concurrency
) VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    provider = EXCLUDED.provider,
    model = EXCLUDED.model,
    api_key = EXCLUDED.api_key,
    base_url = EXCLUDED.base_url,
    input_token_limit = EXCLUDED.input_token_limit,
    output_token_limit = EXCLUDED.output_token_limit,
    temperature = EXCLUDED.temperature,
    timeout = EXCLUDED.timeout,
    max_retries = EXCLUDED.max_retries,
    prompt_preset = EXCLUDED.prompt_preset,
    custom_prompt = EXCLUDED.custom_prompt,
    max_concurrency = EXCLUDED.max_concurrency,
    updated_at = now()
`

type UpsertSummaryModelConfigParams struct {
	Provider         string
	Model            string
	ApiKey           *string
	BaseUrl          *string
	InputTokenLimit  int32
	OutputTokenLimit int32
	Temperature      float64
	Timeout          float64
	MaxRetries       int32
	PromptPreset     string
	CustomPrompt     *string
	MaxConcurrency   int32
}

func (q *Queries) UpsertSummaryModelConfig(ctx context.Context, arg UpsertSummaryModelConfigParams) error {
	_, err := q.db.Exec(ctx, upsertSummaryModelConfig,
		arg.Provider,
		arg.Model,
		arg.ApiKey,
		arg.BaseUrl,
		arg.InputTokenLimit,
		arg.OutputTokenLimit,
		arg.Temperature,
		arg.Timeout,
		arg.MaxRetries,
		arg.PromptPreset,
		arg.CustomPrompt,
		arg.MaxConcurrency,
	)
	return err
}
