CREATE TABLE yukibot_schema_migrations (
    scope text NOT NULL,
    version integer NOT NULL,
    description text NOT NULL,
    checksum text NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (scope, version)
);

CREATE TABLE forwarder_routes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_chat_id bigint NOT NULL,
    source_topic_id bigint,
    destination_chat_id bigint NOT NULL,
    destination_topic_id bigint,
    mode text NOT NULL CHECK (mode IN ('copy', 'forward')),
    filter_json jsonb NOT NULL,
    enabled boolean NOT NULL,
    fallback_to_copy boolean NOT NULL,
    source_username text,
    destination_username text,
    poll_interval_seconds integer CHECK (poll_interval_seconds IS NULL OR poll_interval_seconds >= 60)
);

CREATE INDEX forwarder_routes_source_idx ON forwarder_routes (source_chat_id, enabled);

CREATE TABLE forwarder_message_links (
    route_id bigint NOT NULL REFERENCES forwarder_routes (id) ON DELETE CASCADE,
    source_chat_id bigint NOT NULL,
    source_message_id bigint NOT NULL,
    destination_chat_id bigint NOT NULL,
    destination_message_id bigint NOT NULL,
    delivery_mode text NOT NULL DEFAULT 'copy' CHECK (delivery_mode IN ('copy', 'forward')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (route_id, source_chat_id, source_message_id)
);

CREATE INDEX forwarder_links_source_message_idx ON forwarder_message_links (source_message_id);

CREATE TABLE forwarder_jobs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kind text NOT NULL CHECK (kind IN ('receive', 'edit', 'delete')),
    deduplication_key text NOT NULL UNIQUE,
    group_key text,
    payload_json jsonb NOT NULL,
    state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'processing', 'succeeded', 'failed')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at timestamptz NOT NULL,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX forwarder_jobs_pending_idx ON forwarder_jobs (state, available_at, id);
CREATE INDEX forwarder_jobs_group_idx ON forwarder_jobs (group_key, state, available_at);

CREATE TABLE forwarder_managed_topics (
    source_chat_id bigint NOT NULL,
    source_topic_id bigint NOT NULL DEFAULT 0 CHECK (source_topic_id >= 0),
    destination_chat_id bigint NOT NULL,
    topic_id bigint NOT NULL CHECK (topic_id > 0),
    title text NOT NULL CHECK (length(title) > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (source_chat_id, source_topic_id, destination_chat_id),
    UNIQUE (destination_chat_id, topic_id)
);

CREATE TABLE forwarder_poll_cursors (
    source_chat_id bigint PRIMARY KEY,
    last_message_id bigint NOT NULL CHECK (last_message_id >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE forwarder_chat_access (
    chat_id bigint PRIMARY KEY,
    title text,
    username text,
    invite_link text,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE management_admins (
    user_id bigint PRIMARY KEY,
    granted_by bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE management_modules (
    name text PRIMARY KEY,
    enabled boolean NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE management_command_receipts (
    account_id bigint NOT NULL,
    chat_id bigint NOT NULL,
    message_id bigint NOT NULL,
    processed_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (account_id, chat_id, message_id)
);

CREATE TABLE summarizer_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_chat_id bigint NOT NULL,
    source_topic_id bigint,
    source_username text,
    destination_chat_id bigint NOT NULL,
    destination_topic_id bigint,
    destination_username text,
    window_seconds integer NOT NULL CHECK (window_seconds BETWEEN 60 AND 2592000),
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX summarizer_rules_source_idx ON summarizer_rules (source_chat_id, source_topic_id, enabled);

CREATE TABLE summarizer_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id bigint NOT NULL REFERENCES summarizer_rules (id) ON DELETE CASCADE,
    started_at timestamptz NOT NULL,
    completed_at timestamptz NOT NULL,
    first_message_id bigint NOT NULL CHECK (first_message_id > 0),
    last_message_id bigint NOT NULL CHECK (last_message_id >= first_message_id),
    message_count integer NOT NULL CHECK (message_count > 0),
    provider text NOT NULL,
    model text NOT NULL,
    prompt_version integer NOT NULL CHECK (prompt_version > 0),
    output_json text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX summarizer_runs_rule_idx ON summarizer_runs (rule_id, id DESC);

CREATE TABLE summarizer_model_config (
    id integer PRIMARY KEY CHECK (id = 1),
    provider text NOT NULL,
    model text NOT NULL,
    api_key text,
    base_url text,
    input_token_limit integer NOT NULL,
    output_token_limit integer NOT NULL,
    temperature double precision NOT NULL,
    timeout double precision NOT NULL,
    max_retries integer NOT NULL,
    prompt_preset text NOT NULL DEFAULT 'focused',
    custom_prompt text,
    max_concurrency integer NOT NULL DEFAULT 3,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (input_token_limit > output_token_limit + 2000),
    CHECK (output_token_limit > 0),
    CHECK (temperature BETWEEN 0 AND 2),
    CHECK (timeout > 0 AND timeout <= 1800),
    CHECK (max_retries BETWEEN 0 AND 10),
    CHECK (prompt_preset IN ('focused', 'decisions', 'technical', 'digest')),
    CHECK (custom_prompt IS NULL OR length(custom_prompt) <= 4000),
    CHECK (max_concurrency BETWEEN 1 AND 8)
);
