package forwarder

import "github.com/nhirsama/yukibot/internal/contracts"

// Migrations is the converged PostgreSQL schema for the forwarder.
// It is the end state of the Python SQLite migrations, not a replay of each ALTER.
var Migrations = []contracts.Migration{
	{
		Scope:       "forwarder",
		Version:     1,
		Description: "create forwarding routes, links, jobs, topics, cursors and chat access",
		Statements: []string{
			`CREATE TABLE forwarder_routes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_chat_id bigint NOT NULL,
    source_topic_id bigint,
    destination_chat_id bigint NOT NULL,
    destination_topic_id bigint,
    mode text NOT NULL CHECK (mode IN ('copy', 'forward')),
    filter_json jsonb NOT NULL,
    enabled boolean NOT NULL,
    fallback_to_copy boolean NOT NULL,
    source_username text,
    destination_username text,
    poll_interval_seconds integer CHECK (poll_interval_seconds IS NULL OR poll_interval_seconds >= 60)
)`,
			`CREATE INDEX forwarder_routes_source_idx ON forwarder_routes (source_chat_id, enabled)`,
			`CREATE TABLE forwarder_message_links (
    route_id bigint NOT NULL REFERENCES forwarder_routes (id) ON DELETE CASCADE,
    source_chat_id bigint NOT NULL,
    source_message_id bigint NOT NULL,
    destination_chat_id bigint NOT NULL,
    destination_message_id bigint NOT NULL,
    delivery_mode text NOT NULL DEFAULT 'copy' CHECK (delivery_mode IN ('copy', 'forward')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (route_id, source_chat_id, source_message_id)
)`,
			`CREATE INDEX forwarder_links_source_message_idx ON forwarder_message_links (source_message_id)`,
			`CREATE TABLE forwarder_jobs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kind text NOT NULL CHECK (kind IN ('receive', 'edit', 'delete')),
    deduplication_key text NOT NULL UNIQUE,
    group_key text,
    payload_json jsonb NOT NULL,
    state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'processing', 'succeeded', 'failed')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at timestamptz NOT NULL,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
)`,
			`CREATE INDEX forwarder_jobs_pending_idx ON forwarder_jobs (state, available_at, id)`,
			`CREATE INDEX forwarder_jobs_group_idx ON forwarder_jobs (group_key, state, available_at)`,
			`CREATE TABLE forwarder_managed_topics (
    source_chat_id bigint NOT NULL,
    source_topic_id bigint NOT NULL DEFAULT 0 CHECK (source_topic_id >= 0),
    destination_chat_id bigint NOT NULL,
    topic_id bigint NOT NULL CHECK (topic_id > 0),
    title text NOT NULL CHECK (length(title) > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (source_chat_id, source_topic_id, destination_chat_id),
    UNIQUE (destination_chat_id, topic_id)
)`,
			`CREATE TABLE forwarder_poll_cursors (
    source_chat_id bigint PRIMARY KEY,
    last_message_id bigint NOT NULL CHECK (last_message_id >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
)`,
			`CREATE TABLE forwarder_chat_access (
    chat_id bigint PRIMARY KEY,
    title text,
    username text,
    invite_link text,
    updated_at timestamptz NOT NULL DEFAULT now()
)`,
		},
	},
}
