"""Generate the complete frozen Python 3.12 casefold table, or check for drift."""

import argparse
import json
import unicodedata
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if unicodedata.unidata_version != "15.0.0":
        raise SystemExit("Use Python 3.12 (Unicode 15.0.0) to reproduce the migration baseline")
    lines = [
        "// Code generated by scripts/generate_casefold.py; DO NOT EDIT.",
        "// Unicode 15.0.0, Python 3.12 str.casefold; identity entries are omitted.",
        "",
        "package textutil",
        "",
        "var casefoldTable = map[rune]string{",
    ]
    for point in range(0x110000):
        if 0xD800 <= point <= 0xDFFF:
            continue
        char = chr(point)
        if char.casefold() != char:
            folded = json.dumps(char.casefold(), ensure_ascii=False)
            lines.append(f"\t0x{point:06X}: {folded},")
    lines.append("}\n")
    text = "\n".join(lines)
    path = Path(__file__).resolve().parents[1] / "internal/textutil/casefold_table.go"
    if args.check:
        if path.read_text() != text:
            raise SystemExit("Casefold table differs; regenerate with Python 3.12 and review")
    else:
        path.write_text(text)


if __name__ == "__main__":
    main()
